//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Entity_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHobby
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> HobbyId { get; set; }
    
        public virtual Hobby Hobby { get; set; }
        public virtual User User { get; set; }
    }
}
